# Generated by Django 5.1.7 on 2025-04-02 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tariff_coef', models.DecimalField(decimal_places=2, max_digits=5)),
                ('increase_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contract_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('days_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('schedule_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('percent_experience', models.IntegerField(default=2)),
                ('month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')])),
                ('bonus_service', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('year', models.IntegerField()),
                ('sick_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vacation_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('maternity_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unpaid_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'db_table': 'payroll_employeesalary',
                'ordering': ['-created_at'],
            },
        ),
    ]
