# Generated by Django 5.1.7 on 2025-04-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='salary',
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='bonus',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='final_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='maternity_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='sick_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='unpaid_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='vacation_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='bonus_service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='contract_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='days_worked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='increase_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='maternity_days',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='percent_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='schedule_days',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='sick_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='tariff_coef',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='unpaid_days',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='vacation_days',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
