# Generated by Django 5.1.7 on 2025-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_employeesalary_salary_employeesalary_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='pension_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='union_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
