# Generated by Django 5.1.7 on 2025-04-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employeesalary_income_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='health_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Выплата на оздоровление'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='material_assistance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Материальная помощь'),
        ),
    ]
