# Generated by Django 5.1.7 on 2025-04-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_employeesalary_health_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='health_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='material_assistance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
