# Generated by Django 5.1.7 on 2025-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_employeesalary_tax_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='taxable_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Налогооблагаемая база'),
        ),
    ]
