# Generated by Django 5.1.7 on 2025-04-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_employeesalary_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Премия'),
        ),
    ]
