# Generated by Django 5.1.7 on 2025-04-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_employeesalary_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Премия'),
        ),
    ]
