# Generated by Django 5.1.7 on 2025-04-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_alter_employeesalary_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='salary',
        ),
    ]
